package programmsettings.exceptions.exceptionwordsfileprocessing;

import programmsettings.exceptions.MainSettingsException;

public class ExceptionFilesArrayIsNotNullAndEmpty extends MainSettingsException {
}
